# Minimal working pre-commit config for agent-kanban
repos:
  # Python formatting and linting with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff-format
        files: ^(backend/|src/|tests/|.*\.py$)
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^(backend/|src/|tests/|.*\.py$)

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^(.tmux_orchestrator/status\.json)$
      - id: check-yaml
        exclude: ^(.github/workflows/|.*\.yml\.j2$)
      - id: check-added-large-files
        args: [--maxkb=1000]

# Configuration for CI mode
ci:
  autofix_prs: false
  autoupdate_schedule: weekly
