"""Update auth system with roles and refresh tokens

Revision ID: a3243c705614
Revises: a5b0a703b795
Create Date: 2025-08-10 22:27:44.005489

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3243c705614"
down_revision: Union[str, Sequence[str], None] = "a5b0a703b795"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "role", sa.Enum("ADMIN", "PM", "AGENT", "VIEWER", name="userrole"), nullable=False
        ),
    )
    op.add_column("users", sa.Column("last_login", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_login")
    op.drop_column("users", "role")
    # ### end Alembic commands ###
