"""Add authentication models

Revision ID: f0a59d52113c
Revises: a3243c705614
Create Date: 2025-08-10 22:29:12.516363

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "f0a59d52113c"
down_revision: Union[str, Sequence[str], None] = "a3243c705614"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
